apiVersion: v1
kind: Service
metadata:
  name: highpeaks-flowise-service
spec:
  type: NodePort
  selector:
    app: highpeaks-flowise
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
